install ack
install ctags
install fasd
install figlet
install gawk
install git
install grc
install hub
install imagemagick
install macvim --override-system-vim
install mcabber
install npm
install reattach-to-user-namespace
install the_silver_searcher
install tmux
install tree
install vim
install weechat
install wget
install zsh

# quicklook plugins
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch
cask install quicklook-csv
cask install betterzipql
cask install webp-quicklook

# browsers
cask install google-chrome
cask install chromium
cask install firefox

# tools
cask install alfred
cask install iterm2
cask install imagealpha
cask install imageoptim
cask install licecap
cask install macvim
cask install slate
cask install transmission

update
