#!/usr/bin/env bash
# Usage: sway launch
# Summary: Launch extra apps
# Help: Mostly used when I step in the office for email, messages, etc
#
#    sway launch [work]
#    sway launch [quit]

set -e

ACTION=${1}
CMD="open -a"

case $ACTION in

  work )
  for APP in "Feeds.app" "Fantastical.app" "Frank DeLoupe.app" "MailTab Pro for Gmail.app" "Droplr.app"
  do
    $CMD "/Applications/$APP"
  done
  ;;

  quit )
  for APP in "Feeds" "Fantastical" "Frank DeLoupe" "MailTab Pro for Gmail" "Droplr"
  do
    killall "$APP"
  done
  ;;

esac
