#!/bin/sh
#
# Collects info on your commit and sends it off to Jira
#
branch=$(git rev-parse --abbrev-ref HEAD | sed -e "s'^.*/''")
comment=$(git log -n 1)
~/projects/team/scripts/jiracomment -s $branch -m "$comment"
JIRA_EXIT="$?"

if [ $JIRA_EXIT -ne 0 ]; then
  if [ "$JIRA_EXIT" -eq 4 ]; then
    osascript -e "display notification \"JIRA issue $branch does not exist!\" with title \"jiracomment failed!\""
  elif [ "$JIRA_EXIT" -eq 3 ]; then
    osascript -e 'display notification "Authorization Failed! Maybe you need to jiracomment --auth?" with title "jiracomment failed!"'
  else
    osascript -e 'display notification "Unexpected Error" with title "jiracomment failed!"'
  fi
  exit 1
fi

# Copy last commit hash to clipboard on commit
git log -l --format=format:%h | pbcopy
